server:
  port: 9000
logging:
  config:
    classpath: log4j2.xml

bee:
  provider:
    name: kafka1x  #servlet,kafka1x
    kafka1x:
      idleSleep: 5000 #队列为空时候，线程休眠时间，默认100ms
      pollTimeout: 2000 #kafka拉取超时时间，默认1000ms
      topics: bee-default,bee-process,bee-process-param,bee-sql,bee-sql-param,bee-request,bee-request-param,bee-logger
      kafkaConfig:
        #kafka配置值项，项名称和值请参考kafka文档
        bootstrap.servers: 127.0.0.1:9092
        max.poll.records: 5 #默认500
  store:
    name: console
    elasticsearch:
      url: http://192.168.1.24:9200
#      username: xx
#      password: xx
#      connTimeout: 6000
#      readTimeout: 6000
#      defaultMaxTotalConnectionPerRoute: 2
      indices:
        def: bee-comm-def
        process: bee-comm-process
        request: bee-comm-request
        sql: bee-comm-sql
        sqlp: bee-comm-sql-param
        tx: bee-comm-tx
        log: bee-comm-logger
        param: bee-comm-param
        err : bee-comm-error
  handlers:
    flow: empty>json>queue>store
    queue:
      queueSize: 5000 #队列大小，默认5000
      threadNum: 2 #默认cpu核数
      sleep: 100
      batchSize: 100
      maxLoopTimes: 3