logger:
    level: debug
plugins:
    process:
        spend: 1
        typesMatch:
            include:
                nameEquals:
                nameStartsWith:
                nameEndsWith:
                nameContains:
                nameMatches:
            exclude:
                nameEquals:
                nameStartsWith:
                nameEndsWith:
                nameContains:
                nameMatches:
        methodMatch:
            include:
                nameEquals:
                nameStartsWith:
                nameEndsWith:
                nameContains:
                nameMatches:
            exclude:
                nameEquals:
                nameStartsWith:
                nameEndsWith:
                nameContains:
                nameMatches:
